# Referenced
# http://blog.crowdint.com/2013/05/24/android-builds-on-travis-ci-with-gradle.html
# on 17-02-15
language: android
jdk: oraclejdk6
env:
  matrix:
    - ANDROID_TARGET=android-17  ANDROID-ABI=armeabi-v7a

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-17.0.0

    # The SDK version used to compile your project
    - android-17

    # Additional components
    - addon-google_apis-google-17

    # Specify at least one system image
    - sys-img-x86-android-17

# Emulator Management: Create, Start and Wait
before_script:
   - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
   - emulator -avd test -no-skin -no-audio -no-window &
   - android-wait-for-emulator
   - adb shell input keyevent 82 &

before_install:
    # Gradle
    - wget http://services.gradle.org/distributions/gradle-1.6-bin.zip
    - unzip gradle-1.6-bin.zip
    - export GRADLE_HOME=$PWD/gradle-1.6
    - export PATH=$GRADLE_HOME/bin:$PATH

notifications:
  slack: cmput301w15t07:uuNgHWzxTHVkpkrfmUfqZPov
